version: '3.7'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ${POSTGRES_DB:-crystal_to_do_test}
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
